package a98apps.pingnoads.view;

import android.support.design.widget.AppBarLayout;
import android.support.design.widget.TabLayout;
import android.support.v4.view.ViewPager;
import android.support.v7.app.AlertDialog;
import android.support.v7.widget.Toolbar;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.RelativeLayout;
import android.widget.Spinner;
import android.widget.TextView;

public class ViewHolder{

    public Button buttonPing;
    public TextView addressIpv4;
    public TextView addressIpv6;
    public TextView connectionType;
    public TextView totalPacketLoss;
    public RelativeLayout wifiInfo;
    public TextView gatewayText;
    public TextView dns1Text;
    public TextView dns2Text;
    public TextView maskText;
    public TextView macText;
    public RelativeLayout macLayout;
    public RelativeLayout mobileDns;
    public TextView operatorText;
    public RelativeLayout mobileDnsOther;
    public RelativeLayout operatorLayout;
    public RelativeLayout typeConnectionLayout;
    public TextView typeConnectionName;
    public TextView dns1MobileText;
    public TextView dns2MobileText;
    public TextView dns3MobileText;
    public TextView dns4MobileText;
    public RelativeLayout ipv4Layout;
    public RelativeLayout ipv6Layout;
    public TextView buttonLoadIp;
    public RelativeLayout layoutExternalIp;
    public ListView listaPing;
    TextView intervalSpeed;
    RelativeLayout packetLayout;
    RelativeLayout layoutSettingTextSize;
    Spinner spinnerTextSize;
    CheckBox floatMode;
    EditText inputHost;
    Spinner spinnerInterval;
    TextView version;
    MainActivity.SectionsPagerAdapter mSectionsPagerAdapter;
    ViewPager mViewPager;
    TabLayout tabLayout;
    Toolbar toolbar;
    AlertDialog settingsDialog;
    AlertDialog helpDialog;
    TextView tab1;
    TextView tab2;
    AppBarLayout.LayoutParams params;
    CheckBox seePacket;
    Spinner spinnerCount;
    RelativeLayout layoutCustomCount;
    EditText inputCustomCount;
    Button buttonReset;
    RelativeLayout customInterval;
    EditText inputCustom;
    Button helpEnablePacket;
    Button helpCount;
    Button helpInterval;
    CheckBox pingOnly;
    Button helpPingOnly;
    AlertDialog helpItem;
    AlertDialog confirmDialog;
    Spinner spinnerPingMode;
    Button helpPingMode;
    EditText inputBytes;
    Button helpBytes;
    Button helpFloatMode;
    Spinner spinnerRecent;
    Button helpTextSize;
}
